configured_endpoints: 168
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/modern-treasury%2Fmodern-treasury-ccffb7bd38de82d6f015e0dd2dfcc53116dfe97249d22adb20e94e724f0eec6b.yml
openapi_spec_hash: 9d2b7e9e5ac074b72e8ca49f2fb32f4f
config_hash: a72bd4a2ac1f162cd206781c0f397c9e
