#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Detecting breaking changes"

TEST_PATHS=(
	client_test.go
	moderntreasury_test.go
	connection_test.go
	counterparty_test.go
	event_test.go
	expectedpayment_test.go
	externalaccount_test.go
	incomingpaymentdetail_test.go
	invoice_test.go
	invoicelineitem_test.go
	document_test.go
	accountcollectionflow_test.go
	accountdetail_test.go
	routingdetail_test.go
	internalaccount_test.go
	internalaccountbalancereport_test.go
	ledger_test.go
	ledgeraccountcategory_test.go
	ledgeraccount_test.go
	ledgeraccountbalancemonitor_test.go
	ledgeraccountstatement_test.go
	ledgerentry_test.go
	ledgertransaction_test.go
	ledgertransactionversion_test.go
	lineitem_test.go
	paymentflow_test.go
	paymentorder_test.go
	paymentorderreversal_test.go
	paymentreference_test.go
	return_test.go
	transaction_test.go
	transactionlineitem_test.go
	validation_test.go
	virtualaccount_test.go
	bulkrequest_test.go
	bulkresult_test.go
	ledgeraccountsettlement_test.go
	ledgeraccountsettlementaccountentry_test.go
	foreignexchangequote_test.go
	connectionlegalentity_test.go
	legalentity_test.go
	legalentityassociation_test.go
	paymentaction_test.go
	journalentry_test.go
	journalreport_test.go
	hold_test.go
	usage_test.go
	paginationauto_test.go
	paginationmanual_test.go
)

for PATHSPEC in "${TEST_PATHS[@]}"; do
    # Try to check out previous versions of the test files
    # with the current SDK.
    git checkout "$1" -- "${PATHSPEC}" 2>/dev/null || true
done

# Instead of running the tests, use the linter to check if an
# older test is no longer compatible with the latest SDK.
./scripts/lint
